export const ENDPOINT = "https://yugipedia.com/api.php"
export const MEDIA_ENDPOINT = "https://yugipedia.com/wiki/Special:FilePath"
export const SPECIAL_BROWSE_ENDPOINT = "https://yugipedia.com/wiki/Special:Browse"
export const WIKI_ENDPOINT = "https://yugipedia.com/wiki"
export const INDEX_ENDPOINT = "https://yugipedia.com/index.php"
